backend:
  name: github
  repo: recruiterz/study
collections:
  - create: true
    fields:
      - label: Title
        name: title
      - label: Description
        name: description
      - label: Coffee
        name: coffee
      - label: Date
        name: date
        widget: date
      - label: Body
        name: body
        widget: markdown
    folder: content/meetup
    label: meetup
    name: meetup
media_folder: content/assets
